# Generates Styles/PackIcons.xaml Geometry resources from Material Symbols SVG files.
# Usage: .\scripts\Generate-PackIcons.ps1 [-IconsDir path] [-OutputFile path]

param(
    [string]$IconsDir = (Join-Path $PSScriptRoot "..\Assets\icons-pack\icons"),
    [string]$OutputFile = (Join-Path $PSScriptRoot "..\Styles\PackIcons.xaml")
)

$ErrorActionPreference = "Stop"
$IconsDir = [System.IO.Path]::GetFullPath($IconsDir)
$OutputFile = [System.IO.Path]::GetFullPath($OutputFile)

if (-not (Test-Path $IconsDir)) {
    throw "Icons directory not found: $IconsDir"
}

function Get-SvgPathData([string]$svgContent) {
    $matches = [regex]::Matches($svgContent, '\bd="([^"]+)"')
    if ($matches.Count -eq 0) { return $null }
    return ($matches | ForEach-Object { $_.Groups[1].Value }) -join ' '
}

function Escape-Xaml([string]$text) {
    return $text.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;')
}

function To-ResourceKey([string]$fileName) {
    $base = [System.IO.Path]::GetFileNameWithoutExtension($fileName) -replace '-', '_'
    return "PackIcon_$base"
}

$geometries = @{}
Get-ChildItem -Path $IconsDir -Filter "*.svg" | Sort-Object Name | ForEach-Object {
    $pathData = Get-SvgPathData (Get-Content $_.FullName -Raw)
    if ($pathData) {
        $geometries[(To-ResourceKey $_.Name)] = $pathData
    }
}

# Semantic aliases -> source pack key
$aliases = [ordered]@{
    IconDashboard          = 'PackIcon_dialpad'
    IconHistory            = 'PackIcon_rss_feed'
    IconContacts           = 'PackIcon_contacts'
    IconHoldGeometry       = 'PackIcon_call_hold'
    IconHoldActiveGeometry = 'PackIcon_call_unhold'
    IconMuteGeometry       = 'PackIcon_mic_on'
    IconMuteOffGeometry    = 'PackIcon_mic_off'
    IconRecordGeometry     = 'PackIcon_record'
    IconConferenceGeometry = 'PackIcon_conference'
    IconTransferGeometry   = 'PackIcon_transfer_within_a_station'
    IconPhone              = 'PackIcon_call'
    IconClose              = 'PackIcon_cancel'
    IconSearch             = 'PackIcon_search'
    IconBackspace          = 'PackIcon_backspace'
    IconCallEnd            = 'PackIcon_call_end'
    IconDelete             = 'PackIcon_delete'
    IconAdd                = 'PackIcon_add'
    IconEdit               = 'PackIcon_edit'
    IconCallMade           = 'PackIcon_call_made'
    IconCallReceived       = 'PackIcon_call_received'
    IconCallMissed         = 'PackIcon_call_missed'
    IconDialpad            = 'PackIcon_dialpad'
    IconSms                = 'PackIcon_mobile_sound'
    IconVoicemail          = 'PackIcon_volume_up'
}

$lines = @(
    '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"'
    '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"'
    '                    xmlns:controls="clr-namespace:CallAnalog.Softphone.Views.Controls">'
    '    <!-- Auto-generated by scripts/Generate-PackIcons.ps1 -->'
    ''
    '    <!-- Material Symbols geometries (960-space, Y offset applied in PackIcon) -->'
)

foreach ($entry in ($geometries.GetEnumerator() | Sort-Object Key)) {
    $escaped = Escape-Xaml $entry.Value
    $lines += "    <Geometry x:Key=`"$($entry.Key)`">$escaped</Geometry>"
}

$lines += ''
$lines += '    <!-- Semantic aliases -->'
foreach ($alias in $aliases.Keys) {
    $sourceKey = $aliases[$alias]
    if (-not $geometries.ContainsKey($sourceKey)) {
        Write-Warning "Alias $alias references missing key $sourceKey"
        continue
    }
    $escaped = Escape-Xaml $geometries[$sourceKey]
    $lines += "    <Geometry x:Key=`"$alias`">$escaped</Geometry>"
}

$lines += @(
    ''
    '    <!-- Shared PackIcon styles -->'
    '    <Style x:Key="NavPackIcon" TargetType="controls:PackIcon">'
    '        <Setter Property="IconSize" Value="18" />'
    '        <Setter Property="HorizontalAlignment" Value="Center" />'
    '        <Setter Property="VerticalAlignment" Value="Center" />'
    '    </Style>'
    ''
    '    <Style x:Key="HeaderPackIcon" TargetType="controls:PackIcon">'
    '        <Setter Property="IconSize" Value="14" />'
    '        <Setter Property="HorizontalAlignment" Value="Center" />'
    '        <Setter Property="VerticalAlignment" Value="Center" />'
    '    </Style>'
    ''
    '    <Style x:Key="InCallPackIcon" TargetType="controls:PackIcon">'
    '        <Setter Property="IconSize" Value="20" />'
    '        <Setter Property="HorizontalAlignment" Value="Center" />'
    '        <Setter Property="VerticalAlignment" Value="Center" />'
    '    </Style>'
    ''
    '    <Style x:Key="ActionPackIcon" TargetType="controls:PackIcon">'
    '        <Setter Property="IconSize" Value="14" />'
    '        <Setter Property="HorizontalAlignment" Value="Center" />'
    '        <Setter Property="VerticalAlignment" Value="Center" />'
    '    </Style>'
    ''
    '    <Style x:Key="SearchPackIcon" TargetType="controls:PackIcon">'
    '        <Setter Property="IconSize" Value="16" />'
    '        <Setter Property="HorizontalAlignment" Value="Center" />'
    '        <Setter Property="VerticalAlignment" Value="Center" />'
    '        <Setter Property="Foreground" Value="{StaticResource PhoneTextTertiaryBrush}" />'
    '    </Style>'
    ''
    '    <!-- Fill-based Material path inside Viewbox (960-space + Y translate) -->'
    '    <Style x:Key="PackIconPath" TargetType="Path">'
    '        <Setter Property="Stretch" Value="Uniform" />'
    '        <Setter Property="Fill" Value="{Binding RelativeSource={RelativeSource AncestorType=Path}, Path=Tag}" />'
    '        <Setter Property="RenderTransform">'
    '            <Setter.Value>'
    '                <TranslateTransform Y="960" />'
    '            </Setter.Value>'
    '        </Setter>'
    '    </Style>'
    ''
    '    <Style x:Key="NavIconPath" TargetType="Path" BasedOn="{StaticResource PackIconPath}">'
    '        <Setter Property="Width" Value="18" />'
    '        <Setter Property="Height" Value="18" />'
    '        <Setter Property="Fill" Value="{Binding RelativeSource={RelativeSource AncestorType=Button}, Path=Foreground}" />'
    '        <Setter Property="HorizontalAlignment" Value="Center" />'
    '        <Setter Property="VerticalAlignment" Value="Center" />'
    '    </Style>'
    ''
    '    <Style x:Key="InCallIconPath" TargetType="Path" BasedOn="{StaticResource PackIconPath}">'
    '        <Setter Property="Width" Value="20" />'
    '        <Setter Property="Height" Value="20" />'
    '        <Setter Property="Fill" Value="{Binding RelativeSource={RelativeSource AncestorType=Button}, Path=Foreground}" />'
    '        <Setter Property="HorizontalAlignment" Value="Center" />'
    '        <Setter Property="VerticalAlignment" Value="Center" />'
    '    </Style>'
    ''
    '    <Style x:Key="ActionIconPath" TargetType="Path" BasedOn="{StaticResource PackIconPath}">'
    '        <Setter Property="Width" Value="14" />'
    '        <Setter Property="Height" Value="14" />'
    '        <Setter Property="Fill" Value="{Binding RelativeSource={RelativeSource AncestorType=Button}, Path=Foreground}" />'
    '        <Setter Property="HorizontalAlignment" Value="Center" />'
    '        <Setter Property="VerticalAlignment" Value="Center" />'
    '    </Style>'
    ''
    '</ResourceDictionary>'
)

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($OutputFile, $lines, $utf8NoBom)
Write-Host "Generated $($geometries.Count) pack icons + $($aliases.Count) aliases -> $OutputFile"
